app:
  image: ibmcom/swift-ubuntu
  ports:
    - "8090:8090"
  volumes:
    - .:/root/Kitura-Starter-Bluemix
  command: bash -c "make clean -C Kitura-Starter-Bluemix && make -C Kitura-Starter-Bluemix && Kitura-Starter-Bluemix/.build/debug/Kitura-Starter-Bluemix"
